# Generated by Django 4.2.1 on 2023-05-18 15:40

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='mediafiles/', validators=[Petstagram.photos.validators.validate_image_less_than_5mb]),
        ),
    ]
