# Generated by Django 4.2.1 on 2023-05-26 07:50

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='pet_photos/', validators=[Petstagram.photos.validators.validate_image_less_than_5mb]),
        ),
    ]
